### ISSUE TITLE
Latest 2.2.1 release zip file problem

### ISSUE THREAD

**Issue by Dannii-Darkness** [Aviuz/Locks#12]
Cannot open to unzip the contents with 7-zip and Windows says the file is invalid when I try to view the contents in explorer or with 7-zip. Both say that it isn't an archive.

Some strange things:
1. Even though Windows says it isn't an archive and there seems no way for me to view it, Windows Defender still scans 28 files when I tell it to scan it.
2. When I view its property attributes (next to read only/hidden) it says the file is blocked because it has come from another computer and there's a checkbox to unblock it - which I do, but it makes no difference. I've never seen this before on another file.

And lastly, when I try Extract All... using explorer the Extraction Wizard (which I never normally use) says that it is empty.

I tried DLing the file several times to make sure but all the same. Not really sure what's going on here.

Thanks,
Dannii

**Comment by JonnyNova** [comment]
The file is actually a rar. Renaming it to .rar works.
```file Locks.zip 
Locks.zip: RAR archive data, v5```
