### ISSUE TITLE
The right click menu isn't obvious and may be missed by players

### ISSUE THREAD

**Issue by JonnyNova** [Aviuz/Locks#7]
The right click menu on the lock gizmo differs from the normal Rimworld UX and is likely to be missed by players. What would be your thoughts of switching the single lock gizmo into three separate gizmos?

**Comment by Aviuz** [comment]
I do not want to make this mod clutter UI. The simplest use of this mod is to unlock doors. Right-click is for advanced users, and should not take so much space on UI.

Can't satisfy every user.

I do not want to shut down this discussion but for now I cannot see any good reason to change this. Thank you for feedback.

**Comment by JonnyNova** [comment]
Sure. The new inspection tab for v2.0 solves this issue really well. Going to close this one
